# Generated by Django 3.0.4 on 2020-03-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('nb_place', models.IntegerField()),
                ('date_event', models.DateField()),
                ('time_event', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('participate', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
